apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "pleme-attestation-framework.labels" . | nindent 4 }}
    tameshi.pleme.io/managed: "true"
    tameshi.pleme.io/enforced: "true"
